spring:
  datasource:
    url: "jdbc:mysql://localhost/motocatalogdb"
    username: "develop"
    password: "develop"
  sql:
    init:
      mode: always
      encoding: "utf-8"

server:
  port: 8081

logging:
  level:
    root: info

  # ファイル出力
  file:
    name: app.log

  # ログローテーション
  logback:
    rollingpolicy:
      max-file-size: 1MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
